on:
    push:
        branches:
            - dev

name: Latest frontend build push to Azure

jobs:
    build-and-deploy:
        env:
            DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
            IMAGE_VERSION: dev
            ACR: ${{ secrets.REGISTRY_LOGIN_SERVER }}

        runs-on: ubuntu-latest
        steps:
            - name: 'Checkout GitHub Action'
              uses: actions/checkout@master

            - name: 'Login via Azure CLI'
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: 'Build image'
              run: |
                  docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/studentidrett-frontend:dev

            - name: 'Run tests'
              run: docker test

            - name: 'Push image to ACR'
              uses: azure/docker-login@v1
              with:
                  login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
                  username: ${{ secrets.REGISTRY_USERNAME }}
                  password: ${{ secrets.REGISTRY_PASSWORD }}
            - run: |
                  docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/studentidrett-frontend:dev
            - name: Azure logout
              run: |
                  az logout
