on:
    pull_request:
        branches:
            - dev

name: Frontend build and test

jobs:
    build-and-deploy:
        env:
            DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
            IMAGE_VERSION: ${{ github.actor }}
            ACR: ${{ secrets.REGISTRY_LOGIN_SERVER }}

        runs-on: ubuntu-latest
        steps:
            - name: 'Checkout GitHub Action'
              uses: actions/checkout@master

            - name: 'Build image and run tests'
              run: |
                  docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/studentidrett-frontend:${{ github.actor }}

